# Permalinks
permalink:        pretty
markdown: kramdown

# Setup
url:             http://zvtoth.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:        ''

title:            Zita V. Tóth

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      Lecturer in Philosophy <br> (King's College London)


# The tags listed as entries in the sidebar
sidebar_tags:

# Fallback image and color if not overwritten for tag or post
image:           /public/img/tree.jpg
color:            '#b14633'

author:
  name:           'Zita V. Tóth'
  email:           zita.v.toth@kcl.ac.uk
  facebook:     zita.v.toth
  linkedin:      tothzita
  academia:   ZitaToth
  philpeople: zita-toth
  instagram:  oresmeember
  gscholar: tothzit
  orcid: 0000-0002-0767-1099

  photo:          /public/img/zvt.jpg

  about: I am a Lecturer in the History of Philosophy at King's College London. My main interests are later medieval philosophy, philosophy of religion, and metaphysics.
