# Permalinks
permalink:        pretty
markdown: kramdown

# Setup
url:             http://zvtoth.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:        ''

title:            Zita V. Tóth

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      Postdoctoral Researcher <br> (KU Leuven)


# The tags listed as entries in the sidebar
sidebar_tags:

# Fallback image and color if not overwritten for tag or post
image:           /public/img/tree.jpg
color:            '#b14633'

author:
  name:           'Zita V. Tóth'
  email:           zita.toth@kuleuven.be
  facebook:     zita.v.toth
  github:         zvtoth
  linkedin:      tothzita
  academia:   ZitaToth
  instagram:  oresmeember

  photo:          /public/img/zvt.jpg

  about: I am a Postdoctoral Research Fellow at KU Leuven, in Belgium, working on a project centered on "Hylomorphism Whole, 1300--1330." My main interests are later medieval philosophy, philosophy of religion, and metaphysics.
